export const TYPES = {
    AUTH_LOGIN: "AUTH_LOGIN",
    AUTH_LOGIN_ASYNC: "AUTH_LOGIN_ASYNC",
    DISMISS_ALERT: "DISMISS_ALERT",
    SET_DATA_PACKAGES: "SET_DATA_PACKAGES",
    AUTH_LOGOUT: "AUTH_LOGOUT"
} 